;$Id: spacesdemo.make,v 1.2.2.10 2009/12/22 23:36:40 yhahn Exp $

core = "6.x"

projects[admin][version] = "2"
projects[cck][version] = "2"
projects[context][version] = "3"
projects[ctools][version] = "1"
projects[data][version] = "1"
projects[designkit][version] = "1"
projects[devel][version] = "1"
projects[diff][version] = "2"
projects[features][version] = "1"
projects[feeds][version] = "1"
projects[imageapi][version] = "1"
projects[imagecache][version] = "2"
projects[jquery_ui][version] = "1"
projects[og][version] = "2"
projects[purl][version] = "1"
projects[simpletest][version] = "2.8"
projects[spaces][version] = "3"
projects[strongarm][version] = "2"
projects[views][version] = "2"

projects[atrium_reader][location] = "http://code.developmentseed.org/fserver"
projects[jupiter][location] = "http://code.developmentseed.org/fserver"
projects[rubik][location] = "http://code.developmentseed.org/fserver"
projects[tao][location] = "http://code.developmentseed.org/fserver"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "modules/jquery_ui"